# Generated by Django 3.2.8 on 2021-10-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('aisle', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('original', models.CharField(max_length=200)),
                ('originalName', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('possibleUnits', models.CharField(choices=[('piece', 'piece'), ('slice', 'slice'), ('fruit', 'fruit'), ('g', 'grams'), ('oz', 'ounces'), ('cup', 'cups'), ('serving', 'servings')], default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=200)),
                ('diets', models.CharField(max_length=200)),
                ('servings', models.IntegerField(blank=True)),
                ('sourceName', models.CharField(max_length=200)),
                ('sourceUrl', models.URLField(blank=True)),
                ('spoonacularSourceUrl', models.URLField(blank=True)),
                ('healthScore', models.FloatField(blank=True)),
                ('spoonacularScore', models.FloatField(blank=True)),
                ('calories', models.IntegerField(blank=True)),
                ('carbs', models.IntegerField(blank=True)),
                ('fat', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('protein', models.IntegerField(blank=True)),
                ('maxReadyTime', models.IntegerField(blank=True)),
                ('includeNutrition', models.BooleanField(default=True)),
                ('extendedIngredients', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
