# Generated by Django 3.2.8 on 2021-10-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='aisle',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='healthScore',
            new_name='ingredient_amount',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='extendedIngredients',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='maxReadyTime',
            new_name='prep_time',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='sourceName',
            new_name='sourcename',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='sourceUrl',
            new_name='sourceurl',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='original',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='originalName',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='includeNutrition',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='spoonacularScore',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='spoonacularSourceUrl',
        ),
        migrations.AddField(
            model_name='receipe',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='tag',
            field=models.ManyToManyField(blank=True, to='receipes_app.Tag'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
