# Generated by Django 3.2.8 on 2021-10-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0002_auto_20211030_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='possibleUnits',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='receipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
