# Generated by Django 3.2.8 on 2021-10-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0003_auto_20211030_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='possibleUnits',
            field=models.CharField(choices=[('piece', 'piece'), ('slice', 'slice'), ('fruit', 'fruit'), ('g', 'grams'), ('oz', 'ounces'), ('cup', 'cups'), ('serving', 'servings')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='receipe',
            name='unit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
