# Generated by Django 3.2.8 on 2021-10-31 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0004_auto_20211030_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='possibleUnits',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='unit',
        ),
    ]
