# Generated by Django 3.2.8 on 2021-10-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0005_auto_20211031_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='IngredientAmount',
            field=models.ManyToManyField(blank=True, to='receipes_app.Tag'),
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='possibleUnits',
            field=models.CharField(choices=[('piece', 'piece'), ('slice', 'slice'), ('fruit', 'fruit'), ('g', 'grams'), ('oz', 'ounces'), ('cup', 'cups'), ('serving', 'servings')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='unit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
