# Generated by Django 3.2.8 on 2021-10-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0006_auto_20211031_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='IngredientAmount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.ManyToManyField(blank=True, to='receipes_app.IngredientAmount'),
        ),
    ]
