# Generated by Django 3.2.8 on 2021-10-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0009_auto_20211031_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='ingredient',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
