# Generated by Django 3.2.8 on 2021-10-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0011_remove_receipe_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='possibleUnits',
        ),
        migrations.AddField(
            model_name='receipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='receipes_app.Ingredient'),
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='ingredient_amount',
        ),
        migrations.AddField(
            model_name='receipe',
            name='ingredient_amount',
            field=models.ManyToManyField(blank=True, to='receipes_app.IngredientAmount'),
        ),
    ]
