# Generated by Django 3.2.8 on 2021-10-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0012_auto_20211031_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='ingredient_amount',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='IngredientAmount', to='receipes_app.Ingredient'),
        ),
    ]
