# Generated by Django 3.2.8 on 2021-10-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0013_auto_20211031_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='receipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipes_app.receipe'),
        ),
    ]
