# Generated by Django 3.2.8 on 2021-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0015_alter_receipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='diets',
            field=models.CharField(choices=[('Gluten Free', 'Gluten Free'), ('Ketogenic', 'Ketogenic'), ('Vegetarian', 'Vegetarian'), ('Lacto-Vegetarian', 'Lacto-Vegetarian'), ('Ovo-Vegetarian', 'Ovo-Vegetarian'), ('Vegan', 'Vegan'), ('Pescetarian', 'Pescetarian'), ('Paleo', 'Paleo'), ('Primal', 'Primal'), ('Low FODMAP', 'Low FODMAP'), ('Whole30', 'Whole30')], default=None, max_length=200),
        ),
    ]
