# Generated by Django 3.2.8 on 2021-11-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0017_auto_20211101_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='image',
            new_name='image_URL',
        ),
    ]
