# Generated by Django 3.2.8 on 2021-11-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0018_rename_image_receipe_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='sourcename',
            new_name='name_of_source',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='sourceurl',
            new_name='source_URL',
        ),
    ]
