# Generated by Django 3.2.8 on 2021-11-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0020_auto_20211101_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='select_Type_of_Unit',
            new_name='select_type_of_unit',
        ),
    ]
