# Generated by Django 3.2.8 on 2021-11-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0021_rename_select_type_of_unit_ingredientamount_select_type_of_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='receipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipes_app.ingredient'),
        ),
    ]
