# Generated by Django 3.2.8 on 2021-11-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0022_alter_ingredientamount_receipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='Ingredient', to='receipes_app.IngredientAmount'),
        ),
    ]
