# Generated by Django 3.2.8 on 2021-11-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0024_auto_20211101_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='ingrediant',
            new_name='ingredient',
        ),
    ]
