# Generated by Django 3.2.9 on 2021-11-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0025_rename_ingrediant_ingredientamount_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
