# Generated by Django 3.2.9 on 2021-11-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0026_receipe_receipe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='image_URL',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_id',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='source_URL',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='tag',
        ),
    ]
