# Generated by Django 3.2.9 on 2021-11-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0027_auto_20211109_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='instructions',
        ),
    ]
