# Generated by Django 3.2.9 on 2021-11-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0030_receipe_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='prep_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
