# Generated by Django 3.2.9 on 2021-11-09 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0032_alter_receipe_prep_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='prep_time',
        ),
    ]
