# Generated by Django 3.2.9 on 2021-11-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0033_remove_receipe_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='calories',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='receipe',
            name='carbs',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='receipe',
            name='fat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='receipe',
            name='protein',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
