# Generated by Django 3.2.9 on 2021-11-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0037_remove_cuisine_grocery_aisle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='receipe',
            name='cuisine',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
