# Generated by Django 3.2.9 on 2021-11-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0038_auto_20211111_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='cuisine',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
