# Generated by Django 3.2.9 on 2021-11-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0039_alter_receipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='cuisine',
            field=models.CharField(choices=[('African', 'African'), ('American', 'American'), ('British', 'British'), ('Cajun', 'Cajun'), ('Caribbean', 'Caribbean'), ('Chinese', 'Chinese'), ('Eastern European', 'Eastern European'), ('European', 'European'), ('French', 'French'), ('German', 'German'), ('Greek', 'Greek'), ('Indian', 'Indian'), ('Irish', 'Irish'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Jewish', 'Jewish'), ('Korean', 'Korean'), ('Latin American', 'Latin American'), ('Mediterranean', 'Mediterranean'), ('Mexican', 'Mexican'), ('Middle Eastern', 'Middle Eastern'), ('Nordic', 'Nordic'), ('Southern', 'Southern'), ('Spanish', 'Spanish'), ('Thai', 'Thai'), ('Vietnamese', 'Vietnamese')], default=None, max_length=200),
        ),
    ]
