# Generated by Django 3.2.9 on 2021-11-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0040_alter_receipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='cuisine',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
