# Generated by Django 3.2.9 on 2021-11-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0041_alter_receipe_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='tag',
            field=models.ManyToManyField(blank=True, to='receipes_app.Tag'),
        ),
    ]
