# Generated by Django 3.2.9 on 2021-11-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0043_auto_20211111_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='diets',
        ),
    ]
