# Generated by Django 3.2.9 on 2021-11-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0044_auto_20211113_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='receipes_app.Ingredient'),
        ),
    ]
