# Generated by Django 3.2.9 on 2021-11-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0045_receipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='cuisine',
            field=models.ManyToManyField(blank=True, to='receipes_app.Cuisine'),
        ),
    ]
