# Generated by Django 3.2.9 on 2021-11-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0049_auto_20211113_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='rating',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
