# Generated by Django 3.2.9 on 2021-11-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0051_alter_receipe_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='rating',
        ),
    ]
