# Generated by Django 3.2.9 on 2021-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0052_remove_receipe_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='receipe',
        ),
        migrations.AddField(
            model_name='receipe',
            name='ingredient_amount',
            field=models.ManyToManyField(blank=True, to='receipes_app.IngredientAmount'),
        ),
    ]
