# Generated by Django 3.2.9 on 2021-11-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0053_auto_20211113_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientamount',
            name='receipe1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipes_app.receipe'),
        ),
    ]
