# Generated by Django 3.2.9 on 2021-11-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0055_rename_receipe1_ingredientamount_orig_receipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='ingredient_amount',
        ),
    ]
