# Generated by Django 3.2.9 on 2021-11-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0056_remove_receipe_ingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='ingredient_amount',
            field=models.ManyToManyField(blank=True, to='receipes_app.IngredientAmount'),
        ),
    ]
