# Generated by Django 3.2.9 on 2021-11-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0058_rename_ingredient_ingredientamount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='image_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
