# Generated by Django 3.2.9 on 2021-11-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0059_alter_receipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='prep_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
