# Generated by Django 3.2.9 on 2021-11-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0060_receipe_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='number_of_reviews',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
