# Generated by Django 3.2.9 on 2021-11-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0061_auto_20211115_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='orig_receipe',
            new_name='receipe_name',
        ),
    ]
