# Generated by Django 3.2.9 on 2021-11-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0062_rename_orig_receipe_ingredientamount_receipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='name_of_source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='source_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='receipes_app.Tag'),
        ),
    ]
