# Generated by Django 3.2.9 on 2021-11-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0063_auto_20211118_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='ingredient_amount',
            field=models.ManyToManyField(blank=True, editable=False, to='receipes_app.IngredientAmount'),
        ),
    ]
