# Generated by Django 3.2.9 on 2021-11-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0064_alter_receipe_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='ingredient_amount',
            field=models.ManyToManyField(blank=True, to='receipes_app.IngredientAmount'),
        ),
    ]
