# Generated by Django 3.2.9 on 2021-12-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0067_auto_20211204_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='image_URL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
