# Generated by Django 3.2.9 on 2021-12-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes_app', '0070_alter_receipe_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='grocery_aisle',
        ),
    ]
